version: '3'
services:
  bff:
    build: ./bff
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - webnet

  mf_drawer:
    build: ./mf_drawer
    ports:
      - "3001:80"
    networks:
      - webnet

  mf_videos:
    build: ./mf_videos
    ports:
      - "3002:80"
    networks:
      - webnet

networks:
  webnet:
